### ISSUE TITLE
[rfe] add option for silent redirect (remove message about redirection)

### ISSUE THREAD

**Issue by njogun** [glensc/dokuwiki-plugin-pageredirect#1]
Add option to silently redirect a user i.e. remove the message "you were redirected from page" from the top of the page.

Syntax could be something like "\~~REDIRECT>namespace:page|silent~~" or similar.

Thanks.

**Comment by glensc** [comment]
reopening as need to document this

**Comment by njogun** [comment]
Please explain. This is a 3-year old issue opened by me. Is it in-progress, wont-fix, resolved or what?

**Comment by glensc** [comment]
i leave it open to document your findings. there is no progress at all in this plugin. haven't got into looking this plugin issues.

**Comment by njogun** [comment]
My understanding is that there **is** something to code - the issue asks for an enhancement to be implemented. The example given in the original report is an example syntax, not something that actually works and needs to be documented.

If you still work on this plugin and plan to implement this enhancement some time in the future, I agree to let it remain opened, otherwise it should be closed.

**Comment by glensc** [comment]
documented

https://www.dokuwiki.org/plugin:pageredirect#configuration
