### ISSUE TITLE
Redirection msg not showing original page name.

### ISSUE THREAD

**Issue by FilSalustri** [glensc/dokuwiki-plugin-pageredirect#13]
Since upgrading to Ponder Stibbons, I've noticed a problem with this plugin.
Used to be that once redirected, the page showed a message at the top with a message "You were redirected here from XYZ" where XYZ is the page I tried to access and was redirected from.
Now, however, the XYZ is missing and I just see "You were redirected here from ."

**Comment by hartmut27** [comment]
I confirm this bug exists in Release 2014-09-29a "Hrun".

**Comment by glensc** [comment]
#15 merged
