### ISSUE TITLE
Redirection message no longer includes link back to redirecting page.

### ISSUE THREAD

**Issue by FilSalustri** [glensc/dokuwiki-plugin-pageredirect#23]
As of Detritus (I think), there appears to be a bug in Page Redirect, which should be evident from the attached PNG.
When I look at the generated HTML, it seems that the right tags & CSS are there, but the A tag has no content. Unfortunately, I lack the PHP skills to figure out why this is happening.
I should note that I am using my own skin - though I kind of think that shouldn't matter.
![dkredirectionbug](https://cloud.githubusercontent.com/assets/7852355/11866022/45c5708c-a476-11e5-8e69-8d4de969a9d1.png)

UPDATE: When I try to look at the redirecting page (e.g. as in http://deseng.ryerson.ca/dokuwiki/:design:pss?redirect=no), I get the following error.
![dkredirectionbug2](https://cloud.githubusercontent.com/assets/7852355/11866203/81385cbe-a477-11e5-9f56-f8a1c77543d6.png)

**Comment by glensc** [comment]
the fatal error got fixed in a04bcd9

**Comment by glensc** [comment]
i think the other problem was fixed with #15. if it is not please post your details
