### ISSUE TITLE
Internal section links

### ISSUE THREAD

**Issue by jayqi** [glensc/dokuwiki-plugin-pageredirect#24]
The plugin does not seem to be properly working with [internal section links](https://www.dokuwiki.org/wiki:syntax#internal).

For example, I am trying to redirect the page ``bayes_theorem`` to ``probability_basic_definitions#bayes_theorem``. I confirmed that the URL ending with

    /doku.php?id=probability_basic_definitions#bayes_theorem

properly returns the page ``probability_basic_definitions`` and scrolled down to the section ``bayes_theorem``. 

However, when I put the redirect on the ``bayes_theorem`` page

    ~~REDIRECT>probability_basic_definitions#bayes_theorem~~

the URL that gets redirected to is

    /doku.php?id=probability_basic_definitions&redirect=1#bayes_theoremid=bayes_theorem

and it puts me at the top of the ``probability_basic_definitions`` page and **not** scrolled down to the section ``bayes_theorem``.

**Comment by glensc** [comment]
seems this got broken from #15 with 5cd681d

**Comment by glensc** [comment]
should be fixed with 5cd681d
