### ISSUE TITLE
Redirect URL adding page Name

### ISSUE THREAD

**Issue by AdamKhanIT** [glensc/dokuwiki-plugin-pageredirect#25]
Hi,

I installed the plugin. 
Used the following syntax to redirect a page nagios to a particular url for example like below.

```
~~REDIRECT>http://google.com~~ 
```

Its adding the page name to the end of the URL when i click on the page it takes me to http://google.comid%3Dnagios/   (my page name is nagios) any idea why its appending this?

**Comment by glensc** [comment]
seems this got broken from #15 with 5cd681d

**Comment by glensc** [comment]
fixed by revert 5cd681d from #16
